/**
 * Which strings count as a usable public invite link.
 *
 * This predicate is load-bearing in a way that is easy to miss: the invite UI
 * gates on it, so a link it fails to recognise does not merely look odd, it
 * DISAPPEARS from the screen behind a "Generate" button. That is exactly what
 * happened when the accept-list pinned `localhost:3000` while the web client had
 * moved to Vite's `:5173` — a real, already-published link became invisible on
 * mobile, and the failure gave no clue as to why.
 *
 * The two halves pinned here pull in opposite directions and both matter:
 *
 *   - ACCEPT broadly. The link is produced by whichever client the Space owner
 *     used, not by this one. Refusing an origin we would not ourselves generate
 *     means rejecting a valid invite from a peer.
 *   - REJECT the `quorum://join#…` value, which is not an invite link at all.
 *     kickUser writes it into the same `space.inviteUrl` field, so anything
 *     gating on mere truthiness would offer members a dead link to share after
 *     any kick.
 */

// The predicates under test are pure string work, but they live in a module that
// reaches the Rust crypto module and MMKV at import time. Both are stubbed so the
// import graph resolves under jest; neither is exercised by these tests.
jest.mock('@/services/crypto/native-provider', () => ({ NativeCryptoProvider: class {} }));
jest.mock('react-native-mmkv', () => ({
  createMMKV: () => {
    const store = new Map<string, string>();
    return {
      getString: (k: string) => store.get(k),
      set: (k: string, v: string) => store.set(k, v),
      remove: (k: string) => store.delete(k),
      delete: (k: string) => store.delete(k),
      getAllKeys: () => Array.from(store.keys()),
      clearAll: () => store.clear(),
      contains: (k: string) => store.has(k),
    };
  },
}));

import { isPublicInvite, parseInviteLink } from '@/services/space/inviteService';

const SPACE_ID = 'QmPeerAbcdefghijklmnopqrstuvwxyz012345678901234';
const CONFIG_KEY = 'ab'.repeat(56);
const publicHash = `#spaceId=${SPACE_ID}&configKey=${CONFIG_KEY}`;

describe('recognising a public invite link', () => {
  describe('accepts links generated by any client', () => {
    it.each([
      ['production short domain', `https://qm.one/invite/${publicHash}`],
      ['production app domain', `https://app.quorummessenger.com/invite/${publicHash}`],
      ['staging', `https://test.quorummessenger.com/invite/${publicHash}`],
      // The regression that prompted this file: the web client's dev server.
      ['localhost on Vite 5173', `http://localhost:5173/invite/${publicHash}`],
      ['localhost on 3000', `http://localhost:3000/invite/${publicHash}`],
      ['127.0.0.1 with a port', `http://127.0.0.1:8081/invite/${publicHash}`],
    ])('%s', (_label, link) => {
      expect(isPublicInvite(link)).toBe(true);
      expect(parseInviteLink(link)?.spaceId).toBe(SPACE_ID);
    });

    it('does not care which port localhost happens to use', () => {
      // Enumerating ports is the thing that rotted last time.
      for (const port of [3000, 4200, 5173, 8081, 19006]) {
        expect(isPublicInvite(`http://localhost:${port}/invite/${publicHash}`)).toBe(true);
      }
    });
  });

  describe('rejects things that are not a shareable public link', () => {
    it('rejects the quorum:// value kickUser writes into inviteUrl', () => {
      // Truthy, same field, completely unusable. This is the case a truthiness
      // gate gets wrong, and the reason the UI must call this predicate.
      const afterKick = `quorum://join#spaceId=${SPACE_ID}&configKey=${CONFIG_KEY}`;
      expect(isPublicInvite(afterKick)).toBe(false);
    });

    it('rejects a one-time link, which carries a template and secret', () => {
      const oneTime =
        `https://qm.one/#spaceId=${SPACE_ID}&configKey=${CONFIG_KEY}` +
        `&template=abcdef&secret=123456&hubKey=deadbeef`;
      expect(isPublicInvite(oneTime)).toBe(false);
    });

    it('rejects empty, malformed and unrelated URLs', () => {
      for (const bad of [
        '',
        'not a link at all',
        'https://example.com/invite/#spaceId=x&configKey=y',
        'https://qm.one/invite/',
      ]) {
        expect(isPublicInvite(bad)).toBe(false);
      }
    });
  });
});
